# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "netbox-ubuntu"
  # Allow more than default 300 seconds, as usually VM takes longer
  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"

  ############################################################
  # Configure Vagrant to use VirtualBox:
  ############################################################
  config.vm.provider "virtualbox" do |vb|
    # Netbox-docker with OS consistently uses 1.0 GB of RAM
    # 1.5 to 2 GB or RAM helps with better response
    vb.memory = 2048
    # Docker container management can be CPU intensive
    vb.cpus = 2
  end

  ############################################################
  # Install netbox-docker requirements
  ############################################################

  # Install Docker and Docker Compose
  config.vm.provision :docker
  # For Docker Compose, install required plugin: vagrant plugin install vagrant-docker-compose
  config.vm.provision :docker_compose

  config.vm.provision "shell", inline: <<-SHELL
    # Update and install
    apt-get update
    apt-get install -y git
    apt-get -y autoremove

    # Get netbox-docker as vagrant user
    # per https://github.com/netbox-community/netbox-docker#quickstart
    sudo -H -u vagrant sh -c 'git clone -b release https://github.com/netbox-community/netbox-docker.git'

    echo "To start NetBox, go to /home/vagrant/netbox-docker"
    echo "Ensure the docker-compose.override.yml file is present and run:"
    echo "docker-compose pull"
    echo "docker-compose up"

  SHELL

  # Copy over the docker-compose.override.yml file
  config.vm.provision "file", source: "./docker-compose.override.yml", destination: "/home/vagrant/netbox-docker/docker-compose.override.yml"

end
